name: Fetch ALB and Target Group Information

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch_alb_and_target_group_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Fetch ALB and Target Group Information
        id: fetch_info
        run: |
          # Replace "your-server-name" with the actual name of your server tag.
          # Replace "server-tag-key" and "your-server-tag-value" with the actual key and value of your server tag.
          # For example, if your server tag key is "Name" and its value is "WebServer", replace "Name" with "server-tag-key" and "WebServer" with "your-server-tag-value".
          instance_ids=$(aws ec2 describe-instances --filters "Name=tag:My1stVM,Values=your-server-name" --query "Reservations[*].Instances[*].InstanceId" --output text)

          # Find the target group ARN based on the instance IDs
          target_group_arn=$(aws elbv2 describe-target-groups --query "TargetGroups[?contains(Tags[?Key=='server-tag-key' && Value=='your-server-tag-value'], 'true')].TargetGroupArn" --output text)

          # Find the load balancers using the target group
          alb_arns=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(TargetGroups[].TargetGroupArn, '$target_group_arn')].{Name: LoadBalancerName, ARN: LoadBalancerArn, DNS: DNSName}" --output json)

          # Extract listener port and certificate details for HTTPS listeners
          for alb_arn in $(echo "$alb_arns" | jq -r '.[].ARN'); do
              https_listeners=$(aws elbv2 describe-listeners --load-balancer-arn "$alb_arn" --query "Listeners[?Port==\`443\`]" --output json)
              alb_name=$(echo "$alb_arns" | jq -r ".[] | select(.ARN == \"$alb_arn\").Name")
              alb_dns=$(echo "$alb_arns" | jq -r ".[] | select(.ARN == \"$alb_arn\").DNS")
              
              for listener in $(echo "$https_listeners" | jq -c '.[]'); do
                  listener_port=$(echo "$listener" | jq -r '.Port')
                  listener_arn=$(echo "$listener" | jq -r '.ListenerArn')
                  listener_rules=$(aws elbv2 describe-rules --listener-arn "$listener_arn" --query "Rules[*].[Priority, Actions]" --output json)
                  
                  echo "ALB Name: $alb_name, ARN: $alb_arn, DNS: $alb_dns"
                  echo "Listener Port: $listener_port"
                  
                  echo "Listener Rules:"
                  for rule in $(echo "$listener_rules" | jq -c '.[]'); do
                      rule_priority=$(echo "$rule" | jq -r '.[0]')
                      rule_actions=$(echo "$rule" | jq -r '.[1]')
                      echo "  Rule Priority: $rule_priority"
                      echo "  Rule Actions:"
                      for action in $(echo "$rule_actions" | jq -c '.[]'); do
                          action_type=$(echo "$action" | jq -r '.Type')
                          if [ "$action_type" == "forward" ]; then
                              target_group_arn=$(echo "$action" | jq -r '.TargetGroupArn')
                              echo "    Forward to Target Group ARN: $target_group_arn"
                          fi
                      done
                  done
                  
                  echo "Certificate Details:"
                  certificate_arn=$(aws elbv2 describe-listener-certificates --listener-arn "$listener_arn" --query "Certificates[0].CertificateArn" --output text)
                  certificate_details=$(aws acm describe-certificate --certificate-arn "$certificate_arn" --query "Certificate.[DomainName,SubjectAlternativeNames[],NotBefore,NotAfter]" --output json)
                  echo "$certificate_details"
                  echo ""
                  
                  echo "ALB Members:"
                  targets=$(aws elbv2 describe-target-health --target-group-arn "$target_group_arn" --query "TargetHealthDescriptions[*].[Target.Id, TargetHealth.State]" --output json)
                  for target in $(echo "$targets" | jq -c '.[]'); do
                      target_id=$(echo "$target" | jq -r '.[0]')
                      target_state=$(echo "$target" | jq -r '.[1]')
                      echo "  Target ID: $target_id, State: $target_state"
                  done
                  echo ""
              done
          done
