name: Terraform Workflow

on:
  push:
    branches:
      - main
        


 
jobs:
  aws_action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: 'workflow setup'
# Code checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# configure aws credentials for action
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
# Setup terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
          
# Initialize terraform
      - name: Terraform Init
        run: terraform init 
        working-directory: tfroot # this is directory where all terraform files are
      - name: Refresh Terraform state
        run: terraform refresh
  


